using Plugin.Maui.Audio;
using Squarebuzz.Presentation.Services;

namespace Squarebuzz.App.Services;

/// <inheritdoc />
public sealed class AudioService : IAudioService, IDisposable
{
    /// <summary>
    /// Shortest gap between two plays of the same sound.
    /// </summary>
    /// <remarks>
    /// Dragging across a row fires <see cref="GameSound.Fill"/> once per cell, which on a fast
    /// swipe can be a dozen times in a couple of hundred milliseconds. Restarting a 70 ms blip
    /// every 20 ms is not a dozen blips, it is a buzz. Throttling turns a fast drag into an
    /// audible rattle instead, and costs nothing at ordinary tapping speed.
    /// </remarks>
    private static readonly TimeSpan MinimumGap = TimeSpan.FromMilliseconds(45);

    /// <summary>Asset file name per sound. Generated by <c>tools/generate-sounds.cs</c>.</summary>
    private static readonly Dictionary<GameSound, string> Files = new()
    {
        [GameSound.Fill] = "fill.wav",
        [GameSound.Cross] = "cross.wav",
        [GameSound.Erase] = "erase.wav",
        [GameSound.LineComplete] = "line.wav",
        [GameSound.Hint] = "hint.wav",
        [GameSound.Win] = "win.wav",
    };

    private const string MusicFile = "music.wav";

    /// <summary>
    /// The loop is mixed well below the effects in the file itself; this trims it further so it
    /// sits under them rather than alongside.
    /// </summary>
    private const double MusicVolume = 0.6;

    private readonly IAudioManager _manager;
    private readonly Dictionary<GameSound, IAudioPlayer> _players = [];
    private readonly Dictionary<GameSound, DateTimeOffset> _lastPlayed = [];

    private IAudioPlayer? _music;
    private bool _soundEffectsOn;
    private bool _musicOn;
    private bool _isSuspended;
    private bool _isPrimed;
    private bool _isDisposed;

    public AudioService(IAudioManager manager) => _manager = manager;

    public async Task PrimeAsync()
    {
        if (_isPrimed)
        {
            return;
        }

        // Set first: a failure part way through must not leave this looking un-primed and invite
        // another attempt on every navigation.
        _isPrimed = true;

        foreach (var (sound, file) in Files)
        {
            if (await LoadAsync(file, isMusic: false).ConfigureAwait(false) is { } player)
            {
                _players[sound] = player;
            }
        }

        if (await LoadAsync(MusicFile, isMusic: true).ConfigureAwait(false) is { } music)
        {
            music.Loop = true;
            music.Volume = MusicVolume;
            _music = music;
        }

        // Settings may have been applied before the assets finished loading, in which case the
        // music never got its chance to start.
        ApplyMusicState();
    }

    public void Configure(bool soundEffects, bool music)
    {
        _soundEffectsOn = soundEffects;
        _musicOn = music;

        ApplyMusicState();
    }

    public void Play(GameSound sound)
    {
        if (!_soundEffectsOn || _isDisposed || !_players.TryGetValue(sound, out var player))
        {
            return;
        }

        var now = DateTimeOffset.UtcNow;

        if (_lastPlayed.TryGetValue(sound, out var previous) && now - previous < MinimumGap)
        {
            return;
        }

        _lastPlayed[sound] = now;

        try
        {
            // Stop rewinds to the start, so a sound retriggered before it finished replaces itself
            // rather than being ignored.
            player.Stop();
            player.Play();
        }
        catch (Exception)
        {
            // A single failed blip is not worth telling anyone about, and the platform player can
            // throw transiently when the audio focus changes underneath it.
        }
    }

    public void SuspendMusic()
    {
        _isSuspended = true;
        ApplyMusicState();
    }

    public void ResumeMusic()
    {
        _isSuspended = false;
        ApplyMusicState();
    }

    public void Dispose()
    {
        if (_isDisposed)
        {
            return;
        }

        _isDisposed = true;

        foreach (var player in _players.Values)
        {
            Safely(player.Dispose);
        }

        _players.Clear();

        if (_music is { } music)
        {
            Safely(music.Dispose);
            _music = null;
        }
    }

    private async Task<IAudioPlayer?> LoadAsync(string file, bool isMusic)
    {
        try
        {
            // Copied into memory rather than handed to the player as the package stream: the
            // players are kept for the life of the app, and a platform stream over a compressed
            // asset is not something to rely on staying readable that long.
            await using var packaged = await FileSystem.OpenAppPackageFileAsync(file).ConfigureAwait(false);

            var buffer = new MemoryStream();
            await packaged.CopyToAsync(buffer).ConfigureAwait(false);
            buffer.Position = 0;

            return _manager.CreatePlayer(buffer, OptionsFor(isMusic));
        }
        catch (Exception)
        {
            // A missing or unplayable asset makes the game silent, not broken.
            return null;
        }
    }

    /// <summary>
    /// Per-player audio attributes.
    /// </summary>
    /// <remarks>
    /// <para>
    /// These have to be passed to <c>CreatePlayer</c> for each player. Configuring them once on the
    /// builder is not enough - <c>dumpsys audio</c> showed every one of our players registered with
    /// <c>USAGE_UNKNOWN</c> until they were set here.
    /// </para>
    /// <para>
    /// The loop declares itself as music and the effects as sonification, which is what tells
    /// Android to treat a 70 ms blip and an eight-second pad differently when mixing.
    /// </para>
    /// <para>
    /// Version 4.0.0 of the plugin exposes only these two properties - the audio-focus and
    /// iOS session-category options in its documentation are not in the released package yet.
    /// Focus is therefore not managed, so the loop is stopped on backgrounding by hand; see
    /// <c>App.CreateWindow</c>. An incoming call will talk over it rather than pause it.
    /// </para>
    /// </remarks>
    private static AudioPlayerOptions OptionsFor(bool isMusic) => new()
    {
#if ANDROID
        AudioContentType = isMusic
            ? Android.Media.AudioContentType.Music
            : Android.Media.AudioContentType.Sonification,
        AudioUsageKind = Android.Media.AudioUsageKind.Media,
#endif
    };

    /// <summary>
    /// The single place that decides whether the loop should be running, so the three things that
    /// can stop it - the setting, backgrounding, and assets that never loaded - cannot disagree.
    /// </summary>
    private void ApplyMusicState()
    {
        if (_music is not { } music || _isDisposed)
        {
            return;
        }

        var shouldPlay = _musicOn && !_isSuspended;

        Safely(() =>
        {
            if (shouldPlay)
            {
                if (!music.IsPlaying)
                {
                    music.Play();
                }
            }
            else if (music.IsPlaying)
            {
                // Pause, not Stop: coming back from the home screen should not restart the loop
                // from the top of the bar.
                music.Pause();
            }
        });
    }

    private static void Safely(Action action)
    {
        try
        {
            action();
        }
        catch (Exception)
        {
            // See Play: platform players throw on audio-focus changes and on shutdown races.
        }
    }
}
